
export default [
    {name:"ActionScript"},
    {name:"C"},
    {name:"C#"},
    {name:"C++"},
    {name:"Clojure"},
    {name:"CoffeeScript"},
    {name:"CSS"},
    {name:"Dart"},
    {name:"DM"},
    {name:"Elixir"},
    {name:"Go"},
    {name:"Groovy"},
    {name:"Haskell"},
    {name:"HTML"},
    {name:"Java"},
    {name:"JavaScript"},
    {name:"Julia"},
    {name:"Kotlin"},
    {name:"Lua"},
    {name:"MATLAB"},
    {name:"Objective-C"},
    {name:"Perl"},
    {name:"PHP"},
    {name:"PowerShell"},
    {name:"Python"},
    {name:"R"},
    {name:"Ruby"},
    {name:"Rust"},
    {name:"Scala"},
    {name:"Shell"},
    {name:"Swift"},
    {name:"TeX"},
    {name:"TypeScript"},
    {name:"Vim script"}
]